### ISSUE TITLE
while install pod 

### ISSUE THREAD

**Issue by devitinformatix** [Volst/tuyasmart-home-sdk-react-native#4]
give error when try to install pod 

[!] Error installing TuyaSmartHomeKit
[!] /usr/bin/curl -f -L -o /var/folders/85/h59lh3tj2tg74w2_tmyypn_00000gn/T/d20210311-4236-1m4l3t/file.zip https://airtake-public-data.oss-cn-hangzhou.aliyuncs.com/smart/app/package/sdk/ios/TuyaSmartHomeKit-2.10.96.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to airtake-public-data.oss-cn-hangzhou.aliyuncs.com:443 

![tuyaerror](https://user-images.githubusercontent.com/58102939/110779564-b09ad680-8289-11eb-91d8-c7b81c602d3e.png)

**Comment by SpaceK33z** [comment]
Hey, please contact Tuya about this - we don't maintain their pods.
